version: '3'
services:
  alist-strm:
   #build:
   #   context: .
   #   dockerfile: Dockerfile
    image: ghcr.io/sebastian0619/alist-strm:latest
    container_name: alist-strm
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
