version: '3'
services:
  app:
    container_name: alist-strm
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./cache:/app/cache
    environment:
      - TZ=Asia/Shanghai
