version: '3'
services:
  alist-strm:
    build: .
    container_name: alist-strm
    ports:
      - "8081:8081"
    volumes:
      - ./strm:/app/strm
      - ./.env:/app/.env
    restart: unless-stopped
