version: '3'
services:
  alist-strm:
    build: .
    container_name: alist-strm
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai