version: '3'
services:
  alist-strm:
    image: ghcr.io/sebastian0619/alist-strm:latest
    container_name: alist-strm
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
